spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myBlog?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  #更新数据库表结构
    show-sql: true  #sql\u8BED\u53E5\u6253\u5370

logging:
  level:
    root: info
    com.wsk: debug #\u65E5\u5FD7\u7EA7\u522B
  file:
    path: log/blog-dev.log #\u751F\u6210\u65E5\u5FD7\u8DEF\u5F84